workflows:
  android-debug:
    name: Android Debug APK
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Build debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
